# Generated by Django 4.0.7 on 2022-08-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='last_sent_time',
            field=models.DateTimeField(null=True),
        ),
    ]
