# Generated by Django 4.1 on 2022-08-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
