version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=weather
      - POSTGRES_USER=weather_user
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env.example.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A weather worker -l INFO
    volumes:
      - .:/code/weather/
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A weather beat -l INFO
    volumes:
       - .:/code/weather/
    depends_on:
      - redis
      - web
volumes:
  postgres_data: